codecov:
  bot: "codecov-io"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        branches: null
        if_not_found: success
        if_ci_failed: error
        only_pulls: true

parsers:
  v1:
    include_full_missed_files: true

comment: false
